// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cart/v1/cart.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCartReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCartReq) Reset()         { *m = GetCartReq{} }
func (m *GetCartReq) String() string { return proto.CompactTextString(m) }
func (*GetCartReq) ProtoMessage()    {}
func (*GetCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{0}
}

func (m *GetCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCartReq.Unmarshal(m, b)
}
func (m *GetCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCartReq.Marshal(b, m, deterministic)
}
func (m *GetCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCartReq.Merge(m, src)
}
func (m *GetCartReq) XXX_Size() int {
	return xxx_messageInfo_GetCartReq.Size(m)
}
func (m *GetCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCartReq proto.InternalMessageInfo

func (m *GetCartReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetCartReply struct {
	Items                []*GetCartReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetCartReply) Reset()         { *m = GetCartReply{} }
func (m *GetCartReply) String() string { return proto.CompactTextString(m) }
func (*GetCartReply) ProtoMessage()    {}
func (*GetCartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{1}
}

func (m *GetCartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCartReply.Unmarshal(m, b)
}
func (m *GetCartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCartReply.Marshal(b, m, deterministic)
}
func (m *GetCartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCartReply.Merge(m, src)
}
func (m *GetCartReply) XXX_Size() int {
	return xxx_messageInfo_GetCartReply.Size(m)
}
func (m *GetCartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCartReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCartReply proto.InternalMessageInfo

func (m *GetCartReply) GetItems() []*GetCartReply_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetCartReply_Item struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCartReply_Item) Reset()         { *m = GetCartReply_Item{} }
func (m *GetCartReply_Item) String() string { return proto.CompactTextString(m) }
func (*GetCartReply_Item) ProtoMessage()    {}
func (*GetCartReply_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{1, 0}
}

func (m *GetCartReply_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCartReply_Item.Unmarshal(m, b)
}
func (m *GetCartReply_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCartReply_Item.Marshal(b, m, deterministic)
}
func (m *GetCartReply_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCartReply_Item.Merge(m, src)
}
func (m *GetCartReply_Item) XXX_Size() int {
	return xxx_messageInfo_GetCartReply_Item.Size(m)
}
func (m *GetCartReply_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCartReply_Item.DiscardUnknown(m)
}

var xxx_messageInfo_GetCartReply_Item proto.InternalMessageInfo

func (m *GetCartReply_Item) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *GetCartReply_Item) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type DeleteCartReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCartReq) Reset()         { *m = DeleteCartReq{} }
func (m *DeleteCartReq) String() string { return proto.CompactTextString(m) }
func (*DeleteCartReq) ProtoMessage()    {}
func (*DeleteCartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{2}
}

func (m *DeleteCartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCartReq.Unmarshal(m, b)
}
func (m *DeleteCartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCartReq.Marshal(b, m, deterministic)
}
func (m *DeleteCartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCartReq.Merge(m, src)
}
func (m *DeleteCartReq) XXX_Size() int {
	return xxx_messageInfo_DeleteCartReq.Size(m)
}
func (m *DeleteCartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCartReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCartReq proto.InternalMessageInfo

func (m *DeleteCartReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteCartReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCartReply) Reset()         { *m = DeleteCartReply{} }
func (m *DeleteCartReply) String() string { return proto.CompactTextString(m) }
func (*DeleteCartReply) ProtoMessage()    {}
func (*DeleteCartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{3}
}

func (m *DeleteCartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCartReply.Unmarshal(m, b)
}
func (m *DeleteCartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCartReply.Marshal(b, m, deterministic)
}
func (m *DeleteCartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCartReply.Merge(m, src)
}
func (m *DeleteCartReply) XXX_Size() int {
	return xxx_messageInfo_DeleteCartReply.Size(m)
}
func (m *DeleteCartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCartReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCartReply proto.InternalMessageInfo

type AddItemReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int64    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemReq) Reset()         { *m = AddItemReq{} }
func (m *AddItemReq) String() string { return proto.CompactTextString(m) }
func (*AddItemReq) ProtoMessage()    {}
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{4}
}

func (m *AddItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemReq.Unmarshal(m, b)
}
func (m *AddItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemReq.Marshal(b, m, deterministic)
}
func (m *AddItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemReq.Merge(m, src)
}
func (m *AddItemReq) XXX_Size() int {
	return xxx_messageInfo_AddItemReq.Size(m)
}
func (m *AddItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemReq proto.InternalMessageInfo

func (m *AddItemReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddItemReq) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AddItemReq) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddItemReply struct {
	Items                []*AddItemReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddItemReply) Reset()         { *m = AddItemReply{} }
func (m *AddItemReply) String() string { return proto.CompactTextString(m) }
func (*AddItemReply) ProtoMessage()    {}
func (*AddItemReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{5}
}

func (m *AddItemReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemReply.Unmarshal(m, b)
}
func (m *AddItemReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemReply.Marshal(b, m, deterministic)
}
func (m *AddItemReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemReply.Merge(m, src)
}
func (m *AddItemReply) XXX_Size() int {
	return xxx_messageInfo_AddItemReply.Size(m)
}
func (m *AddItemReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemReply proto.InternalMessageInfo

func (m *AddItemReply) GetItems() []*AddItemReply_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type AddItemReply_Item struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddItemReply_Item) Reset()         { *m = AddItemReply_Item{} }
func (m *AddItemReply_Item) String() string { return proto.CompactTextString(m) }
func (*AddItemReply_Item) ProtoMessage()    {}
func (*AddItemReply_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{5, 0}
}

func (m *AddItemReply_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddItemReply_Item.Unmarshal(m, b)
}
func (m *AddItemReply_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddItemReply_Item.Marshal(b, m, deterministic)
}
func (m *AddItemReply_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddItemReply_Item.Merge(m, src)
}
func (m *AddItemReply_Item) XXX_Size() int {
	return xxx_messageInfo_AddItemReply_Item.Size(m)
}
func (m *AddItemReply_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_AddItemReply_Item.DiscardUnknown(m)
}

var xxx_messageInfo_AddItemReply_Item proto.InternalMessageInfo

func (m *AddItemReply_Item) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *AddItemReply_Item) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type UpdateItemReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int64    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemReq) Reset()         { *m = UpdateItemReq{} }
func (m *UpdateItemReq) String() string { return proto.CompactTextString(m) }
func (*UpdateItemReq) ProtoMessage()    {}
func (*UpdateItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{6}
}

func (m *UpdateItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemReq.Unmarshal(m, b)
}
func (m *UpdateItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemReq.Marshal(b, m, deterministic)
}
func (m *UpdateItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemReq.Merge(m, src)
}
func (m *UpdateItemReq) XXX_Size() int {
	return xxx_messageInfo_UpdateItemReq.Size(m)
}
func (m *UpdateItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemReq proto.InternalMessageInfo

func (m *UpdateItemReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateItemReq) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *UpdateItemReq) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type UpdateItemReply struct {
	Items                []*UpdateItemReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateItemReply) Reset()         { *m = UpdateItemReply{} }
func (m *UpdateItemReply) String() string { return proto.CompactTextString(m) }
func (*UpdateItemReply) ProtoMessage()    {}
func (*UpdateItemReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{7}
}

func (m *UpdateItemReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemReply.Unmarshal(m, b)
}
func (m *UpdateItemReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemReply.Marshal(b, m, deterministic)
}
func (m *UpdateItemReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemReply.Merge(m, src)
}
func (m *UpdateItemReply) XXX_Size() int {
	return xxx_messageInfo_UpdateItemReply.Size(m)
}
func (m *UpdateItemReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemReply proto.InternalMessageInfo

func (m *UpdateItemReply) GetItems() []*UpdateItemReply_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateItemReply_Item struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemReply_Item) Reset()         { *m = UpdateItemReply_Item{} }
func (m *UpdateItemReply_Item) String() string { return proto.CompactTextString(m) }
func (*UpdateItemReply_Item) ProtoMessage()    {}
func (*UpdateItemReply_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{7, 0}
}

func (m *UpdateItemReply_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemReply_Item.Unmarshal(m, b)
}
func (m *UpdateItemReply_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemReply_Item.Marshal(b, m, deterministic)
}
func (m *UpdateItemReply_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemReply_Item.Merge(m, src)
}
func (m *UpdateItemReply_Item) XXX_Size() int {
	return xxx_messageInfo_UpdateItemReply_Item.Size(m)
}
func (m *UpdateItemReply_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemReply_Item.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemReply_Item proto.InternalMessageInfo

func (m *UpdateItemReply_Item) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *UpdateItemReply_Item) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type DeleteItemReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId               int64    `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemReq) Reset()         { *m = DeleteItemReq{} }
func (m *DeleteItemReq) String() string { return proto.CompactTextString(m) }
func (*DeleteItemReq) ProtoMessage()    {}
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{8}
}

func (m *DeleteItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemReq.Unmarshal(m, b)
}
func (m *DeleteItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemReq.Marshal(b, m, deterministic)
}
func (m *DeleteItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemReq.Merge(m, src)
}
func (m *DeleteItemReq) XXX_Size() int {
	return xxx_messageInfo_DeleteItemReq.Size(m)
}
func (m *DeleteItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemReq proto.InternalMessageInfo

func (m *DeleteItemReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteItemReq) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type DeleteItemReply struct {
	Items                []*DeleteItemReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DeleteItemReply) Reset()         { *m = DeleteItemReply{} }
func (m *DeleteItemReply) String() string { return proto.CompactTextString(m) }
func (*DeleteItemReply) ProtoMessage()    {}
func (*DeleteItemReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{9}
}

func (m *DeleteItemReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemReply.Unmarshal(m, b)
}
func (m *DeleteItemReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemReply.Marshal(b, m, deterministic)
}
func (m *DeleteItemReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemReply.Merge(m, src)
}
func (m *DeleteItemReply) XXX_Size() int {
	return xxx_messageInfo_DeleteItemReply.Size(m)
}
func (m *DeleteItemReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemReply proto.InternalMessageInfo

func (m *DeleteItemReply) GetItems() []*DeleteItemReply_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteItemReply_Item struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemReply_Item) Reset()         { *m = DeleteItemReply_Item{} }
func (m *DeleteItemReply_Item) String() string { return proto.CompactTextString(m) }
func (*DeleteItemReply_Item) ProtoMessage()    {}
func (*DeleteItemReply_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5e54d1e82456df, []int{9, 0}
}

func (m *DeleteItemReply_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemReply_Item.Unmarshal(m, b)
}
func (m *DeleteItemReply_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemReply_Item.Marshal(b, m, deterministic)
}
func (m *DeleteItemReply_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemReply_Item.Merge(m, src)
}
func (m *DeleteItemReply_Item) XXX_Size() int {
	return xxx_messageInfo_DeleteItemReply_Item.Size(m)
}
func (m *DeleteItemReply_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemReply_Item.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemReply_Item proto.InternalMessageInfo

func (m *DeleteItemReply_Item) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *DeleteItemReply_Item) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCartReq)(nil), "cart.v1.GetCartReq")
	proto.RegisterType((*GetCartReply)(nil), "cart.v1.GetCartReply")
	proto.RegisterType((*GetCartReply_Item)(nil), "cart.v1.GetCartReply.Item")
	proto.RegisterType((*DeleteCartReq)(nil), "cart.v1.DeleteCartReq")
	proto.RegisterType((*DeleteCartReply)(nil), "cart.v1.DeleteCartReply")
	proto.RegisterType((*AddItemReq)(nil), "cart.v1.AddItemReq")
	proto.RegisterType((*AddItemReply)(nil), "cart.v1.AddItemReply")
	proto.RegisterType((*AddItemReply_Item)(nil), "cart.v1.AddItemReply.Item")
	proto.RegisterType((*UpdateItemReq)(nil), "cart.v1.UpdateItemReq")
	proto.RegisterType((*UpdateItemReply)(nil), "cart.v1.UpdateItemReply")
	proto.RegisterType((*UpdateItemReply_Item)(nil), "cart.v1.UpdateItemReply.Item")
	proto.RegisterType((*DeleteItemReq)(nil), "cart.v1.DeleteItemReq")
	proto.RegisterType((*DeleteItemReply)(nil), "cart.v1.DeleteItemReply")
	proto.RegisterType((*DeleteItemReply_Item)(nil), "cart.v1.DeleteItemReply.Item")
}

func init() { proto.RegisterFile("api/cart/v1/cart.proto", fileDescriptor_fc5e54d1e82456df) }

var fileDescriptor_fc5e54d1e82456df = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x35, 0xc6, 0x67, 0x1e, 0xf7, 0xe9, 0xf3, 0xbd, 0x29, 0xda, 0x10, 0x5a, 0x90, 0x81, 0x82,
	0xb8, 0x48, 0xaa, 0xee, 0xea, 0xa6, 0xb6, 0x85, 0x22, 0x14, 0x0a, 0x82, 0x1b, 0xa1, 0x94, 0xb4,
	0x19, 0x24, 0x10, 0x93, 0x18, 0x47, 0xc1, 0x85, 0x50, 0xda, 0x4f, 0xe8, 0xa7, 0xf5, 0x17, 0xfa,
	0x21, 0x65, 0xc6, 0x98, 0x8c, 0xa3, 0xb5, 0x50, 0xec, 0x2a, 0xb9, 0x93, 0x93, 0x33, 0xe7, 0xcc,
	0x3d, 0x77, 0xa0, 0x62, 0x87, 0xae, 0xf5, 0x68, 0x47, 0xd4, 0x9a, 0x35, 0xf8, 0xd3, 0x0c, 0xa3,
	0x80, 0x06, 0x48, 0xe3, 0xef, 0xb3, 0x86, 0x71, 0x34, 0x0c, 0x82, 0xa1, 0x47, 0x2c, 0x86, 0xb3,
	0x7d, 0x3f, 0xa0, 0x36, 0x75, 0x03, 0x7f, 0xb2, 0x84, 0xe1, 0x13, 0x80, 0x6b, 0x42, 0x2f, 0xed,
	0x88, 0xf6, 0xc8, 0x18, 0x1d, 0x82, 0x36, 0x9d, 0x90, 0xe8, 0xde, 0x75, 0x74, 0xa5, 0xaa, 0xd4,
	0xd4, 0x5e, 0x9e, 0x95, 0x5d, 0x07, 0x2f, 0xa0, 0x90, 0xc0, 0x42, 0x6f, 0x8e, 0x4e, 0xe1, 0x97,
	0x4b, 0xc9, 0x68, 0xa2, 0x2b, 0x55, 0xb5, 0xf6, 0xa7, 0x69, 0x98, 0xf1, 0x6e, 0xa6, 0x88, 0x32,
	0xbb, 0x94, 0x8c, 0x7a, 0x4b, 0xa0, 0xd1, 0x86, 0x1c, 0x2b, 0xd9, 0x16, 0x6c, 0x41, 0xd8, 0x82,
	0x95, 0x5d, 0x07, 0x19, 0xf0, 0x7b, 0x3c, 0xb5, 0x7d, 0xea, 0xd2, 0xb9, 0x9e, 0xe5, 0x5f, 0x92,
	0x1a, 0xd7, 0xa0, 0x78, 0x45, 0x3c, 0x42, 0xc9, 0x97, 0x42, 0xff, 0x43, 0x49, 0x44, 0x86, 0xde,
	0x1c, 0x0f, 0x00, 0x3a, 0x8e, 0xc3, 0xb5, 0xec, 0xf8, 0x53, 0x14, 0x96, 0xfd, 0x54, 0x98, 0x2a,
	0x09, 0x5b, 0x40, 0x21, 0xe1, 0xde, 0x79, 0x2e, 0x22, 0x6a, 0x7f, 0xe7, 0x72, 0x07, 0xc5, 0x7e,
	0xe8, 0xd8, 0x94, 0xfc, 0x8c, 0xbb, 0x17, 0x05, 0x4a, 0x22, 0x3f, 0x73, 0xd8, 0x5a, 0x77, 0x78,
	0x9c, 0x38, 0x94, 0x80, 0xfb, 0x33, 0xd9, 0x59, 0x35, 0xff, 0xdb, 0x26, 0xb9, 0x11, 0x91, 0x63,
	0xa7, 0x11, 0x09, 0xb8, 0x37, 0x23, 0xcd, 0x27, 0x15, 0x72, 0x2c, 0x96, 0xe8, 0x06, 0xb4, 0x78,
	0x4e, 0xd0, 0xc1, 0xe6, 0xe4, 0x8c, 0x8d, 0xf2, 0xd6, 0x71, 0xc2, 0xe5, 0xe7, 0xb7, 0xf7, 0xd7,
	0x6c, 0x09, 0x15, 0xf9, 0x2c, 0xc7, 0xe3, 0x6e, 0xa1, 0x3e, 0x40, 0x1a, 0x79, 0x54, 0x91, 0x7c,
	0xac, 0x38, 0xf5, 0xad, 0xeb, 0x02, 0x6d, 0x5d, 0xa2, 0xbd, 0x05, 0x2d, 0x0e, 0xad, 0x20, 0x32,
	0x1d, 0x24, 0x41, 0xa4, 0x98, 0x6d, 0xac, 0x73, 0x36, 0x74, 0xa6, 0xd4, 0xb1, 0x44, 0x78, 0x0e,
	0x90, 0x66, 0x44, 0xd0, 0xb9, 0x96, 0x60, 0x41, 0xa7, 0x14, 0x28, 0x9c, 0x61, 0x0c, 0x69, 0x73,
	0x36, 0x9c, 0x6e, 0x32, 0x48, 0x9d, 0xc4, 0x99, 0x8b, 0x7f, 0x83, 0xbf, 0xc2, 0x7d, 0xd9, 0x9e,
	0x35, 0x1e, 0xf2, 0xfc, 0x1e, 0x6c, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xdc, 0xb4, 0x4f,
	0x48, 0x05, 0x00, 0x00,
}
